In [1]:
import numpy as np

In [4]:
#seed fuction is for random function jo bhi isse use krenga uska same number aayega also same number has same randm numbers
np.random.seed(50)

In [5]:
arr = np.random.randint(1,20,(3,3))

In [6]:
arr

array([[17,  1, 12],
       [14,  2,  5],
       [ 7,  6,  7]], dtype=int32)

### Indexing

In [7]:
#0,1,2....pehle row fir coloumn
arr[2]

array([7, 6, 7], dtype=int32)

In [9]:
arr[2][0]

np.int32(7)

In [13]:
arr[2,0]

np.int32(7)

In [10]:
arr[0]

array([17,  1, 12], dtype=int32)

In [11]:
arr[1]

array([14,  2,  5], dtype=int32)

In [14]:
arr = np.random.randint(1,20,(3,5,4))

In [15]:
arr

array([[[14,  6,  3,  8],
        [16,  5, 15,  4],
        [ 7, 12, 18, 11],
        [10,  1,  7,  3],
        [16, 10,  4,  3]],

       [[13,  1,  4,  3],
        [11, 17, 15,  1],
        [ 1, 12,  8, 15],
        [14,  8,  5,  5],
        [ 1, 12,  1, 14]],

       [[14,  2, 10, 12],
        [ 6,  1, 16,  6],
        [ 7,  2,  5,  5],
        [13, 15,  5, 12],
        [ 1,  6,  9, 13]]], dtype=int32)

In [16]:
arr[1]

array([[13,  1,  4,  3],
       [11, 17, 15,  1],
       [ 1, 12,  8, 15],
       [14,  8,  5,  5],
       [ 1, 12,  1, 14]], dtype=int32)

In [17]:
arr[0]

array([[14,  6,  3,  8],
       [16,  5, 15,  4],
       [ 7, 12, 18, 11],
       [10,  1,  7,  3],
       [16, 10,  4,  3]], dtype=int32)

In [18]:
arr[0,1]

array([16,  5, 15,  4], dtype=int32)

In [19]:
arr[0,1,2]

np.int32(15)

In [22]:
arr[1,3,3]

np.int32(5)

### Slicing

In [26]:
arr = np.random.randint(1,20,(5,5))

In [27]:
arr

array([[ 4,  7, 19,  9, 16],
       [ 6, 16,  5,  5, 19],
       [16, 11, 18,  9, 15],
       [12,  8, 10,  2,  9],
       [ 4,  4, 11,  4,  7]], dtype=int32)

In [28]:
#pehle row ki fir coloumn ki(start :upto but not included)
arr[2:4 , 1:3]

array([[11, 18],
       [ 8, 10]], dtype=int32)

In [39]:
arr[2:4 , 0]

array([16, 12], dtype=int32)

In [40]:
arr[2:4, 0:3]

array([[16, 11, 18],
       [12,  8, 10]], dtype=int32)

In [43]:
arr = np.random.randint(1,20,(3,5,4))

In [44]:
arr

array([[[16,  1, 19, 12],
        [ 2, 18, 15, 15],
        [ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12]],

       [[ 2,  6, 14,  4],
        [15,  3,  9,  7],
        [ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16]],

       [[ 4,  5, 10,  5],
        [ 8, 18, 14, 10],
        [15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1]]], dtype=int32)

In [45]:
arr[1]

array([[ 2,  6, 14,  4],
       [15,  3,  9,  7],
       [ 1, 15, 14,  5],
       [17, 15,  5, 12],
       [17, 18, 15, 16]], dtype=int32)

In [80]:
arr[0:2 ]

array([[[16,  1, 19, 12],
        [ 2, 18, 15, 15],
        [ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12]],

       [[ 2,  6, 14,  4],
        [15,  3,  9,  7],
        [ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16]]], dtype=int32)

In [52]:
arr[0:2][0]

array([[16,  1, 19, 12],
       [ 2, 18, 15, 15],
       [ 6,  7, 10,  5],
       [10,  1, 16, 17],
       [18, 17,  5, 12]], dtype=int32)

In [89]:
arr[0:2 , 0]

array([[16,  1, 19, 12],
       [ 2,  6, 14,  4]], dtype=int32)

In [72]:
arr[0:2 , 0 ,1 ]

array([1, 6], dtype=int32)

In [82]:
arr[0:2 , 2]

array([[ 6,  7, 10,  5],
       [ 1, 15, 14,  5]], dtype=int32)

In [94]:
arr[0:2, 0:2]

array([[[16,  1, 19, 12],
        [ 2, 18, 15, 15]],

       [[ 2,  6, 14,  4],
        [15,  3,  9,  7]]], dtype=int32)

In [99]:
arr[0:2 , 0:2 , 1]

array([[ 1, 18],
       [ 6,  3]], dtype=int32)

In [100]:
arr[0:2 , 0:2 , 1:3]

array([[[ 1, 19],
        [18, 15]],

       [[ 6, 14],
        [ 3,  9]]], dtype=int32)

In [104]:
arr[2, 2:]

array([[15, 14, 16,  4],
       [ 7, 13, 11, 15],
       [ 1, 14, 14,  1]], dtype=int32)

In [101]:
#layer2,row 2: , col1:upto col3
arr[2,2:,0:3]

array([[15, 14, 16],
       [ 7, 13, 11],
       [ 1, 14, 14]], dtype=int32)

In [123]:
arr

array([[[16,  1, 19, 12],
        [ 2, 18, 15, 15],
        [ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12]],

       [[ 2,  6, 14,  4],
        [15,  3,  9,  7],
        [ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16]],

       [[ 4,  5, 10,  5],
        [ 8, 18, 14, 10],
        [15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1]]], dtype=int32)

In [106]:
# layer, row, elements, row ,  elements
arr[2,2:,0:3][1:,0:2]

array([[ 7, 13],
       [ 1, 14]], dtype=int32)

In [107]:
arr

array([[[16,  1, 19, 12],
        [ 2, 18, 15, 15],
        [ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12]],

       [[ 2,  6, 14,  4],
        [15,  3,  9,  7],
        [ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16]],

       [[ 4,  5, 10,  5],
        [ 8, 18, 14, 10],
        [15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1]]], dtype=int32)

In [115]:
arr[1:4]

array([[[ 2,  6, 14,  4],
        [15,  3,  9,  7],
        [ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16]],

       [[ 4,  5, 10,  5],
        [ 8, 18, 14, 10],
        [15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1]]], dtype=int32)

In [112]:
arr[:, 1:4]

array([[[ 2, 18, 15, 15],
        [ 6,  7, 10,  5],
        [10,  1, 16, 17]],

       [[15,  3,  9,  7],
        [ 1, 15, 14,  5],
        [17, 15,  5, 12]],

       [[ 8, 18, 14, 10],
        [15, 14, 16,  4],
        [ 7, 13, 11, 15]]], dtype=int32)

In [121]:
# all layers , rows, elements
arr[:, 1:4 , 0]

array([[ 2,  6, 10],
       [15,  1, 17],
       [ 8, 15,  7]], dtype=int32)

In [130]:
# all layers , rows , layer , row, element
arr[:, 1:4][0, 1, 2]

np.int32(10)

In [131]:
arr[:, 1:4, 1:3]

array([[[18, 15],
        [ 7, 10],
        [ 1, 16]],

       [[ 3,  9],
        [15, 14],
        [15,  5]],

       [[18, 14],
        [14, 16],
        [13, 11]]], dtype=int32)

In [133]:
arr1 = np.random.randint(1,50,(5,5,5))

In [134]:
arr1

array([[[ 9, 48, 46, 33, 43],
        [15, 45,  5, 41, 43],
        [43, 33,  8, 37, 26],
        [12, 27, 46, 33, 41],
        [24, 48, 39,  4, 29]],

       [[ 6, 44, 29,  2, 48],
        [36,  4,  1, 47, 43],
        [13, 38, 13, 33, 22],
        [44, 15, 20, 46, 17],
        [34, 20, 48, 44, 33]],

       [[ 5, 46, 42, 16, 19],
        [32, 23,  3,  6,  2],
        [34, 26, 11, 19,  9],
        [15, 18, 16, 29, 34],
        [24, 42, 40, 23, 42]],

       [[21, 29, 20, 20, 47],
        [37,  6,  1, 40, 40],
        [49, 28, 25,  3, 11],
        [10,  7, 42, 38, 46],
        [19, 45, 38, 11, 38]],

       [[16, 14, 22,  8, 39],
        [ 1, 44, 49, 40, 11],
        [15,  8, 27, 36, 26],
        [11, 46, 16,  1, 30],
        [46,  1, 43, 20, 33]]], dtype=int32)

In [136]:
arr1[:,4]

array([[24, 48, 39,  4, 29],
       [34, 20, 48, 44, 33],
       [24, 42, 40, 23, 42],
       [19, 45, 38, 11, 38],
       [46,  1, 43, 20, 33]], dtype=int32)

In [137]:
arr1[:, 2:4, 1:3]

array([[[33,  8],
        [27, 46]],

       [[38, 13],
        [15, 20]],

       [[26, 11],
        [18, 16]],

       [[28, 25],
        [ 7, 42]],

       [[ 8, 27],
        [46, 16]]], dtype=int32)

In [138]:
arr = np.random.randint(1,10,(4,4))

In [139]:
arr

array([[5, 2, 5, 5],
       [6, 9, 3, 3],
       [3, 2, 8, 6],
       [6, 5, 8, 9]], dtype=int32)

In [140]:
#-1 se last row bahr aa jati hai
arr[-1]

array([6, 5, 8, 9], dtype=int32)

In [141]:
arr[-1,1]

np.int32(5)

In [142]:
#u can change the number by positioning 
arr[-1,1] = 9

In [143]:
arr

array([[5, 2, 5, 5],
       [6, 9, 3, 3],
       [3, 2, 8, 6],
       [6, 9, 8, 9]], dtype=int32)

In [144]:
#agr sabhi values ki baat change krni ho
arr[2:,0:2] = 5

In [145]:
arr

array([[5, 2, 5, 5],
       [6, 9, 3, 3],
       [5, 5, 8, 6],
       [5, 5, 8, 9]], dtype=int32)

In [149]:
arr[1:,1:4]=0

In [150]:
arr

array([[5, 2, 5, 5],
       [6, 0, 0, 0],
       [5, 0, 0, 0],
       [5, 0, 0, 0]], dtype=int32)

In [155]:
arr= np.random.randint(1,20,(4,4))

In [156]:
arr

array([[18, 16, 12,  5],
       [13, 19, 19, 11],
       [ 6,  1, 14, 17],
       [ 2,  9,  4,  4]], dtype=int32)

In [167]:
# row and elements
a = arr[-2: , -2:]

In [168]:
a

array([[14, 17],
       [ 4,  4]], dtype=int32)

In [173]:
arr

array([[18, 16, 12, 17],
       [13, 19, 19, 11],
       [ 6,  1, 14, 17],
       [ 2,  9,  4,  4]], dtype=int32)

In [178]:
arr[0,-1]=100

In [183]:
#or  original array me bhi change hogeya 
arr

array([[ 18,  16,  12, 100],
       [ 13,  19,  19,  11],
       [  6,   1,  14, 100],
       [  2,   9,   4,   4]], dtype=int32)

In [182]:
#a mai bhi change ho geya 
a

array([[ 14, 100],
       [  4,   4]], dtype=int32)

In [184]:
arr = np.arange(9)
arr = arr.reshape(3,3)


In [185]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
a= arr

In [202]:
b = arr.copy()

In [203]:
a[0][0] = 50

In [204]:
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [205]:
b[0,0]= 100

In [206]:
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [207]:
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])